[build]
  command = "npx expo export --platform web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  # Set these in Netlify dashboard instead of here for security
  # EXPO_PUBLIC_SUPABASE_URL = ""
  # EXPO_PUBLIC_SUPABASE_ANON_KEY = ""
